language: csharp
before_install:
  - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get install apt-transport-https -y
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.1 -y
script:
  - dotnet restore
  - dotnet build
  - dotnet run 
